services:
  backend:
    image: my-recipes-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: my-recipes-backend-local
    ports:
      - "127.0.0.1:3000:3000"           # expose backend to host ONLY for browser and frontend testing
    environment:
      RECIPES_DIRECTORY: /recipes
      BACKEND_PORT: 3000
    volumes:
      - ./recipes:/recipes    # live recipes for testing
    healthcheck:
      test: [
        "CMD",
        "deno",
        "eval",
        "fetch('http://localhost:3000/health').then(r=>{if(!r.ok)Deno.exit(1)})"
      ]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    image: my-recipes-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: my-recipes-frontend
    ports:
      - "127.0.0.1:5173:80"           # expose frontend to host
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-f",
        "http://localhost"
      ]
      interval: 10s
      timeout: 3s
      retries: 5
