services:
  backend:
    container_name: my-recipes-backend-local
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./recipes:/recipes
      - ./resume:/resume

  frontend:
    container_name: my-recipes-frontend
    ports:
      - "127.0.0.1:5173:80"
