services:
  backend:
    image: ghcr.io/cam-codes/my-recipes-backend:${RELEASE_TAG}
    container_name: my-recipes-backend-prod
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /data/recipes/prod:/recipes:rw
      - /data/resume/prod:/resume:ro
      - /data/ratings/prod:/ratings:rw

  frontend:
    image: ghcr.io/cam-codes/my-recipes-frontend:${RELEASE_TAG}
    container_name: my-recipes-frontend-prod
    ports:
      - "127.0.0.1:80:80"
