services:
  backend:
    image: ghcr.io/cam-codes/my-recipes-backend:${RELEASE_TAG:-latest}  # fallback to latest if no var
    container_name: my-recipes-backend-staging
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - /data/recipes/staging:/recipes:rw
      - /data/resume/staging:/resume:ro
      - /data/ratings/staging:/ratings:rw

  frontend:
    image: ghcr.io/cam-codes/my-recipes-frontend:${RELEASE_TAG:-latest}
    container_name: my-recipes-frontend-staging
    ports:
      - "127.0.0.1:5173:80"
